package com.mossdial.data

import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/** Raised when a stored secret cannot be produced, recovered, or trusted. */
class SecretStoreException(message: String, cause: Throwable? = null) : Exception(message, cause)

/**
 * A versioned AES-GCM envelope built directly on `javax.crypto`.
 *
 * Layout, so the format can be migrated later without guessing:
 *
 * ```
 * offset 0   1 byte   magic
 * offset 1   1 byte   format version
 * offset 2   1 byte   initialisation vector length
 * offset 3   n bytes  initialisation vector
 * offset 3+n m bytes ciphertext with the appended 128-bit GCM tag
 * ```
 *
 * The envelope carries no hint about the plaintext it protects. Callers pass additional
 * authenticated data, normally the secret's name, so a blob cannot be moved to a different
 * slot and still decrypt.
 */
object SecretBox {
    private const val MAGIC = 0x4E
    private const val VERSION = 1
    const val HEADER_BYTES = 3
    private const val MAX_IV_BYTES = 16
    const val TAG_BITS = 128
    const val MAX_PLAINTEXT_BYTES = 1 shl 16
    const val MAX_ENVELOPE_BYTES = HEADER_BYTES + MAX_IV_BYTES + MAX_PLAINTEXT_BYTES + TAG_BITS / 8

    /**
     * Seals [plaintext] with an initialisation vector generated by the key itself.
     *
     * There is deliberately no overload that accepts a caller-supplied IV: Android Keystore
     * refuses one when encrypting, so a second entry point would only ever be a trap. A single
     * path works for both a Keystore key, whose material never leaves the keystore daemon, and
     * an ordinary software key.
     */
    fun seal(key: SecretKey, plaintext: ByteArray, aad: ByteArray): ByteArray {
        val cipher = cipher()
        cipher.init(Cipher.ENCRYPT_MODE, key)
        cipher.updateAAD(aad)
        return wrap(cipher, plaintext, cipher.iv)
    }

    fun open(key: SecretKey, envelope: ByteArray, aad: ByteArray): ByteArray {
        if (envelope.size < HEADER_BYTES + TAG_BITS / 8 || envelope.size > MAX_ENVELOPE_BYTES) {
            throw SecretStoreException("The stored secret is not a valid envelope")
        }
        if ((envelope[0].toInt() and 0xFF) != MAGIC) {
            throw SecretStoreException("The stored secret is not a valid envelope")
        }
        if (envelope[1].toInt() != VERSION) {
            throw SecretStoreException("Unsupported secret format version ${envelope[1].toInt()}")
        }
        val ivLength = envelope[2].toInt()
        if (ivLength <= 0 || ivLength > MAX_IV_BYTES || HEADER_BYTES + ivLength >= envelope.size) {
            throw SecretStoreException("The stored secret is not a valid envelope")
        }
        val iv = envelope.copyOfRange(HEADER_BYTES, HEADER_BYTES + ivLength)
        val ciphertext = envelope.copyOfRange(HEADER_BYTES + ivLength, envelope.size)
        if (ciphertext.size < TAG_BITS / 8) {
            throw SecretStoreException("The stored secret is not a valid envelope")
        }
        return try {
            val cipher = cipher()
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(TAG_BITS, iv))
            cipher.updateAAD(aad)
            cipher.doFinal(ciphertext)
        } catch (error: AEADBadTagException) {
            throw SecretStoreException("The stored secret failed its integrity check", error)
        } catch (error: java.security.GeneralSecurityException) {
            throw SecretStoreException("The stored secret could not be decrypted", error)
        }
    }

    private fun wrap(cipher: Cipher, plaintext: ByteArray, iv: ByteArray): ByteArray {
        if (plaintext.size > MAX_PLAINTEXT_BYTES) {
            throw SecretStoreException("The secret is too large to store")
        }
        val ciphertext = cipher.doFinal(plaintext)
        val envelope = ByteArray(HEADER_BYTES + iv.size + ciphertext.size)
        envelope[0] = MAGIC.toByte()
        envelope[1] = VERSION.toByte()
        envelope[2] = iv.size.toByte()
        iv.copyInto(envelope, HEADER_BYTES)
        ciphertext.copyInto(envelope, HEADER_BYTES + iv.size)
        return envelope
    }

    private fun cipher(): Cipher = Cipher.getInstance("AES/GCM/NoPadding")
}
